### PR TITLE
Remove longLabel requirement in track stanza

### PR DESCRIPTION
**Pull request by cmdcolin**
I tried testing parsing this large (6.9MB) blueprint epigenomes test file for curiousity http://trackhubregistry.org/search/view_trackhub/AWD-aTEBOiLcLSpxF4uT

Parsing this trackHub initially gave an error that longLabel is a required field

I think it seems good as a parser to allow just having no longLabel, so I removed it from the requiredFields and added a test for this

### CODE REVIEW

**Comment by cmdcolin** [comment]
@garrettjstevens could this be merged? I have found multiple track hubs with no long label now

**Comment by cmdcolin** [comment]
Another ex https://ftp.ncbi.nlm.nih.gov/pub/dbVar/sandbox/dbvarhub/hub.txt

**Comment by garrettjstevens** [comment]
Yeah, let's merge it. The spec says longLabel required, but UCSC doesn't seem to be honoring their own spec since they don't require longLabel. I ran `hubCheck` on those hubs and they have some problems, but longLabel is not one of them.

**Comment by garrettjstevens** [comment]
This change now in release 0.1.3

**Pull request merged**
